//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeekProj6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outfit
    {
        public int OutfitID { get; set; }
        public string Name { get; set; }
        public Nullable<int> HeadwearID { get; set; }
        public Nullable<int> TopID { get; set; }
        public Nullable<int> DressID { get; set; }
        public Nullable<int> BottomID { get; set; }
        public Nullable<int> ShoeID { get; set; }
        public Nullable<int> BagID { get; set; }
        public Nullable<int> AccessoryID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Bag Bag { get; set; }
        public virtual Bottom Bottom { get; set; }
        public virtual Dress Dress { get; set; }
        public virtual Hat Hat { get; set; }
        public virtual Sho Sho { get; set; }
        public virtual Top Top { get; set; }
    }
}
